"""make username unique and name nullable

Revision ID: 0b046bd17e2a
Revises: 60d15a6fb801
Create Date: 2026-10-05 22:38:59.105128

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b046bd17e2a"
down_revision: str | Sequence[str] | None = "60d15a6fb801"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        schema="auth",
    )
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"], schema="auth"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_users_username"), "users", schema="auth", type_="unique"
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        schema="auth",
    )
    # ### end Alembic commands ###
