"""add naming convention

Revision ID: 60d15a6fb801
Revises: ece7efaa5f3b
Create Date: 2026-10-05 22:33:02.748882

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60d15a6fb801"
down_revision: str | Sequence[str] | None = "ece7efaa5f3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("oauth_providers_provider_provider_id_key"),
        "oauth_providers",
        schema="auth",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_oauth_providers_provider_provider_id"),
        "oauth_providers",
        ["provider", "provider_id"],
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_oauth_providers_provider_provider_id"),
        "oauth_providers",
        schema="auth",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("oauth_providers_provider_provider_id_key"),
        "oauth_providers",
        ["provider", "provider_id"],
        schema="auth",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
