"""create users and oauth providers

Revision ID: ece7efaa5f3b
Revises:
Create Date: 2026-09-30 17:24:49.198924

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ece7efaa5f3b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("profile_picture", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_email"), "users", ["email"], unique=True, schema="auth"
    )
    op.create_table(
        "oauth_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("GOOGLE", "GITHUB", name="oauthproviders", schema="auth"),
            nullable=False,
        ),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_id"),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_providers", schema="auth")
    op.drop_index(op.f("ix_auth_users_email"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
    # autogenerate never drops enum types
    sa.Enum(name="oauthproviders", schema="auth").drop(op.get_bind(), checkfirst=True)
