
name: CI API
on:
  push:
    paths: [api/**, proto/api/**, codegen/api/generate_api.sh, .github/workflows/ci-api.yml]
  pull_request:
    paths: [api/**, proto/api/**, codegen/api/generate_api.sh, .github/workflows/ci-api.yml]

defaults:
  run:
    working-directory: ./api

jobs:
  lint:
    name: check lint, typing, formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install UV
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
           enable-cache: true
           cache-dependency-glob: api/uv.lock

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: api/.python-version

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the Project
        run: uv sync --locked --all-extras --dev

      - name: Run lint
        run: uv run ruff check .

      - name: Run formatting
        run: uv run ruff format --check .

      - name: Run MyPy
        run: uv run mypy .

  api-test:
    name: Run pytests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install UV
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
           enable-cache: true
           cache-dependency-glob: api/uv.lock

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "api/.python-version"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the Project
        run: uv sync --locked --all-extras --dev

      - name: Run all tests
        run: uv run pytest -v
