
name: CI AUTH

on:
  push:
    paths: [auth/**, proto/auth/**, codegen/generate_auth.sh, ./github/workflows/ci-auth.yml]
  pull_request:
    paths: [auth/**, proto/auth/**, codegen/generate_auth.sh, ./github/workflows/ci-auth.yml]

defaults:
  run:
    working-directory: ./auth

jobs:
  lint:
    name: Check lint, format and typing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install UV
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
           enable-cache: true
           cache-dependepcy-glob: auth/uv.lock

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: auth/.python-version;

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the Project
        run: uv sync --locked --all-extras --dev

      - name: Run lint
        run: uv run ruff check .

      - name: Run formatting
        run: uv run ruff format --check .

      - name: Run MyPy
        run: uv run mypy .

  auth-test:
    name: Run pytests
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      DB_URL: postgresql+asyncpg://test:test@localhost:5432/test
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      GOOGLE_CLIENT_ID: test-client-id
      GOOGLE_CLIENT_SECRET: test-secret
      GOOGLE_REDIRECT_URI: http://localhost/callback
      GITHUB_CLIENT_ID: test-cleint-id
      GITHUB_CLIENT_SECRET: test-secret
      GITHUB_REDIRECT_URI: http://localhost/callback
      JWT_SECRET_KEY: test-secret-key
      LOG_LEVEL: INFO

    steps:
      - uses: actions/checkout@v6

      - name: Install UV
        uses: astral-sh/setup-uv@v9
        with:
           enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the Project
        run: uv sync --locked --all-extras --dev

      - name: Run all tests
        run: uv run pytest -v
